name: Spack Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Spack
      run: |
        git clone https://github.com/spack/spack.git
        export SPACK_ROOT=$PWD/spack
        . $SPACK_ROOT/share/spack/setup-env.sh

    - name: Install gcc 4.8.5
      run: spack install gcc@4.8.5